openapi: 3.0.3
info:
  title: Ingredient and Dish Management API
  description: Specification to manage ingredients and dishes
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
tags:
  - name: Ingredients
paths:
  /ingredients:
    get:
      tags:
        - Ingredients
      summary: Get all ingredients
      description: Returns list of ingredients
      responses:
        200:
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      tags:
        - Ingredients
      summary: Get an ingredient by ID
      description: Returns an ingredient based on its id
      parameters:
        - $ref: '#/components/parameters/IngredientIdentifierPathParameter'
      responses:
        200:
          description: Ingredient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: Ingredient.id=1 is not found

  /ingredients/{id}/stock:
    get:
      tags:
        - Ingredients
      summary: Get stock value of an ingredient at a specific time
      description: Returns the stock value for the ingredient with the provided identifier at the specified time and unit
      parameters:
        - $ref: '#/components/parameters/IngredientIdentifierPathParameter'
        - $ref: '#/components/parameters/AtQueryParameter'
        - $ref: '#/components/parameters/UnitQueryParameter'
      responses:
        200:
          description: Stock value retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StockValue'
        400:
          description: Missing mandatory query parameter
          content:
            text/plain:
              schema:
                type: string
                example: Either mandatory query parameter `at` or `unit` is not provided.
        404:
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: Ingredient.id=1 is not found


components:
  parameters:
    IngredientIdentifierPathParameter:
      in: path
      name: id
      description: Ingredient identifier
      schema:
        type: integer
      required: true
    AtQueryParameter:
      in: query
      name: at
      description: Timestamp at which to retrieve the stock value
      schema:
        type: string
        format: date-time
      required: true
    UnitQueryParameter:
      in: query
      name: unit
      description: Unit of measurement for the stock
      schema:
        $ref: '#/components/schemas/UnitType'
      required: true

  schemas:
    CategoryEnum:
      type: string
      enum:
        - VEGETABLE
        - ANIMAL
        - MARINE
        - DAIRY
        - OTHER
    UnitType:
      type: string
      enum:
        - KG
        - PCS
        - L
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Tomato
        category:
          $ref: '#/components/schemas/CategoryEnum'
        price:
          type: number
          format: float
          example: 2.5
    StockValue:
      type: object
      properties:
        quantity:
          type: number
          format: float
          example: 15.5
        unit:
          $ref: '#/components/schemas/UnitType'