openapi: 3.0.3
info:
  title: Ingredient and Dish Management API
  description: Specification to manage ingredients and dishes
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
tags:
  - name: Ingredients
paths:
  /ingredients:
    get:
      tags:
        - Ingredients
      summary: Get all ingredients
      description: Returns list of ingredients
      responses:
        200:
          description: List of ingredients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ingredient'

  /ingredients/{id}:
    get:
      tags:
        - Ingredients
      summary: Get an ingredient by ID
      description: Returns an ingredient based on its id
      parameters:
        - $ref: '#/components/parameters/IngredientIdentifierPathParameter'
      responses:
        200:
          description: Ingredient found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ingredient'
        404:
          description: Ingredient not found
          content:
            text/plain:
              schema:
                type: string
                example: Ingredient.id=1 is not found


components:
  parameters:
    IngredientIdentifierPathParameter:
      in: path
      name: id
      description: Ingredient identifier
      schema:
        type: integer
      required: true
  schemas:
    CategoryEnum:
      type: string
      enum:
        - VEGETABLE
        - ANIMAL
        - MARINE
        - DAIRY
        - OTHER
    Ingredient:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Tomato
        category:
          $ref: '#/components/schemas/CategoryEnum'
        price:
          type: number
          format: float
          example: 2.5